name: WorldExport

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Export
        run: |
          ProjectName='Project3042';
          LevelName='The New Prison';
          ServerIP="${{ secrets.SECRET_FTP_HOST }}";
          ServerLocation="ftps://${{ secrets.SECRET_FTP_LOGIN }}@$ServerIP/";
          LocalWorldSaves='./saves/';
          DistLocation='./dist/';
          Version=$(cat "$GITHUB_WORKSPACE/MAP-VERSION");
          SrcOverworld="$LocalWorldSaves$ServerIP/$LevelName/";
          SrcNether="$LocalWorldSaves$ServerIP/${LevelName}_nether/";
          RemoteOverworld="$ServerLocation$LevelName/";
          RemoteNether="$ServerLocation${LevelName}_nether/";
          DistFolder="$DistLocation/export";
          DistMapFolder="$DistFolder/$ProjectName World v$Version";

          mkdir -p "$LocalWorldSaves";
          mkdir -p "$DistMapFolder";

          wget -P "$LocalWorldSaves" -r --no-parent "$RemoteOverworld";
          wget -P "$LocalWorldSaves" -r --no-parent "$RemoteNether";

          cp -a "$GITHUB_WORKSPACE/MAP-README " "$DistFolder/READ ME.txt"
          cp -a "${SrcOverworld}data" "$DistMapFolder";
          cp -a "${SrcOverworld}poi" "$DistMapFolder";
          cp -a "${SrcOverworld}region" "$DistMapFolder";
          cp -a "${SrcOverworld}icon.png" "$DistMapFolder";
          cp -a "${SrcOverworld}level.dat" "$DistMapFolder";
          cp -a "${SrcOverworld}uid.dat" "$DistMapFolder";
          cp -a "${SrcNether}DIM-1" "$DistMapFolder";

      - name: Archive Zip File
        uses: actions/upload-artifact@v2
        with:
          name: $ProjectName v$Version.zip
          path: |
            $DistFolder/**
            