name: WorldExport

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2      

        env:
          ProjectName: 'Project3042';
          LevelName: 'The New Prison';
          ServerIP: "${{ secrets.SECRET_FTP_HOST }}";
          ServerLocation: "ftps://${{ secrets.SECRET_FTP_LOGIN }}@${{ env.ServerIP }}/";
          LocalWorldSaves: './saves/';
          DistLocation: './dist/';
          Version: $(cat "$GITHUB_WORKSPACE/MAP-VERSION");
          SrcOverworld: "${{ env.LocalWorldSaves }}${{ env.ServerIP }}/${{ env.LevelName }}/";
          SrcNether: "${{ env.LocalWorldSaves }}${{ env.ServerIP }}/${{ env.LevelName }}_nether/";
          RemoteOverworld: "${{ env.ServerLocation }}${{ env.LevelName }}/";
          RemoteNether: "${{ env.ServerLocation }}${{ env.LevelName }}_nether/";
          DistFolder: "${{ env.DistLocation }}/export";
          DistMapFolder: "${{ env.DistFolder }}/${{ env.ProjectName }} World v${{ env.Version }}";

      - name: Export
        run: |
          mkdir -p "${{ env.LocalWorldSaves }}";
          mkdir -p "${{ env.DistMapFolder }}";

          wget -P "${{ env.LocalWorldSaves }}" -r --no-parent "${{ env.RemoteOverworld }}";
          wget -P "${{ env.LocalWorldSaves }}" -r --no-parent "${{ env.RemoteNether }}";

          cp -a "$GITHUB_WORKSPACE/MAP-README" "${{ env.DistFolder }}/READ ME.txt"
          cp -a "${{ env.SrcOverworld }}data" "${{ env.DistMapFolder }}";
          cp -a "${{ env.SrcOverworld }}poi" "${{ env.DistMapFolder }}";
          cp -a "${{ env.SrcOverworld }}region" "${{ env.DistMapFolder }}";
          cp -a "${{ env.SrcOverworld }}icon.png" "${{ env.DistMapFolder }}";
          cp -a "${{ env.SrcOverworld }}level.dat" "${{ env.DistMapFolder }}";
          cp -a "${{ env.SrcOverworld }}uid.dat" "${{ env.DistMapFolder }}";
          cp -a "${{ env.SrcNether }}DIM-1" "${{ env.DistMapFolder }}";

      - name: Archive Zip File
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ProjectName }} v${{ env.Version }}.zip
          path: |
            ${{ env.DistFolder }}/**/*
            