name: WorldExport

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2      

      - name: Export
        run: |
          SrcOverworld="${{ env.LocalWorldSaves }}${{ env.ServerIP }}/${{ env.LevelName }}/";
          SrcNether="${{ env.LocalWorldSaves }}${{ env.ServerIP }}/${{ env.LevelName }}_nether/";
          RemoteOverworld="${{ env.ServerLocation }}${{ env.LevelName }}/";
          RemoteNether="${{ env.ServerLocation }}${{ env.LevelName }}_nether/";
          DistFolder="${{ env.DistLocation }}/export";
          DistMapFolder="${{ env.DistFolder }}/${{ env.ProjectName }} World v${{ env.Version }}";

          mkdir -p "${{ env.LocalWorldSaves }}";
          mkdir -p "${{ DistMapFolder }}";

          wget -P "${{ env.LocalWorldSaves }}" -r --no-parent "${{ RemoteOverworld }}";
          wget -P "${{ env.LocalWorldSaves }}" -r --no-parent "${{ RemoteNether }}";

          cp -a "$GITHUB_WORKSPACE/MAP-README" "${{ DistFolder }}/READ ME.txt"
          cp -a "${{ SrcOverworld }}data" "${{ DistMapFolder }}";
          cp -a "${{ SrcOverworld }}poi" "${{ DistMapFolder }}";
          cp -a "${{ SrcOverworld }}region" "${{ DistMapFolder }}";
          cp -a "${{ SrcOverworld }}icon.png" "${{ DistMapFolder }}";
          cp -a "${{ SrcOverworld }}level.dat" "${{ DistMapFolder }}";
          cp -a "${{ SrcOverworld }}uid.dat" "${{ DistMapFolder }}";
          cp -a "${{ SrcNether }}DIM-1" "${{ DistMapFolder }}";
        env:
          ProjectName: 'Project3042'
          LevelName: 'The New Prison'
          ServerIP: "${{ secrets.SECRET_FTP_HOST }}"
          ServerLocation: "ftps://${{ secrets.SECRET_FTP_LOGIN }}@${{ env.ServerIP }}/"
          LocalWorldSaves: './saves/'
          DistLocation: './dist/'
          Version: $(cat "$GITHUB_WORKSPACE/MAP-VERSION")

      - name: Archive Zip File
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ProjectName }} v${{ env.Version }}.zip
          path: |
            ${{ env.DistLocation }}/export/**/*
            